name: Continuous Delivery

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to design.scarletbanner.com
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to design.scarletbanner.com
        uses: appleboy/ssh-action@master
        with:
          host: scarletbanner.com
          USERNAME: ${{ secrets.DEPLOYER_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.DEPLOYER_KEY }}
          script: |
            cd ${{ secrets.DEPLOYER_REMOTE_DIR }}
            git pull
            npm install
            npm run prod